version: '3'

services:
  postgres0:
    image: postgres:latest
    networks:
      - ilp-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: -c 'max_prepared_transactions=100'

  iroha0:
    image: hyperledger/iroha:latest
    ports:
      - '50051:50051'
    networks:
      - ilp-network
    environment:
      - IROHA_POSTGRES_HOST=postgres0
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=password
      - KEY=node0
    depends_on:
      - postgres0
    volumes:
      - ./iroha0-data:/opt/iroha_data

  alice-node-redis:
    image: redis:latest
    networks:
      - ilp-network

  bob-node-redis:
    image: redis:latest
    networks:
      - ilp-network
    command: --port 6380

  alice-node:
    image: interledgerrs/ilp-node:latest
    networks:
      - ilp-network
    depends_on:
      - alice-node-redis
    restart: on-failure
    command: [
        '--ilp_address=example.alice',
        '--secret_seed=8852500887504328225458511465394229327394647958135038836332350604',
        '--admin_auth_token=alice_auth_token',
        '--redis_url=redis://alice-node-redis:6379',
        '--http_bind_address=0.0.0.0:7770',
        '--settlement_api_bind_address=0.0.0.0:7771'
      ]

  bob-node:
    image: interledgerrs/ilp-node:latest
    networks:
      - ilp-network
    depends_on:
      - bob-node-redis
    restart: on-failure
    command: [
        '--ilp_address=example.bob',
        '--secret_seed=6178940982650927693716509273967164509826378124457201908738317682',
        '--admin_auth_token=bob_auth_token',
        '--redis_url=redis://bob-node-redis:6380',
        '--http_bind_address=0.0.0.0:8770',
        '--settlement_api_bind_address=0.0.0.0:8771'
      ]

  alice-settlement-redis:
    image: redis:latest
    networks:
      - ilp-network
    command: --port 6381

  bob-settlement-redis:
    image: redis:latest
    networks:
      - ilp-network
    command: --port 6382

  alice-settlement:
    image: groman99/ilp-iroha-settlement:latest
    networks:
      - ilp-network
    depends_on:
      - iroha0
      - alice-settlement-redis
    restart: on-failure
    volumes:
      - ./iroha0-data:/opt/iroha_data
    command: [
        '--torii-url=http://iroha0:50051',
        '--connector-url=http://alice-node:7771',
        '--redis-url=redis://alice-settlement-redis:6381',
        '--iroha-account-id=alice@test',
        '--keypair-name=/opt/iroha_data/alice@test',
        '--asset-id=coin0#test',
        '--asset-scale=2'
      ]

  bob-settlement:
    image: groman99/ilp-iroha-settlement:latest
    networks:
      - ilp-network
    depends_on:
      - iroha0
      - bob-settlement-redis
    restart: on-failure
    volumes:
      - ./iroha0-data:/opt/iroha_data
    command: [
        '--bind-port=3001',
        '--torii-url=http://iroha0:50051',
        '--connector-url=http://bob-node:8771',
        '--redis-url=redis://bob-settlement-redis:6382',
        '--iroha-account-id=bob@test',
        '--keypair-name=/opt/iroha_data/bob@test',
        '--asset-id=coin0#test',
        '--asset-scale=2'
      ]

networks:
  ilp-network:
    driver: bridge
